- name: Check for Docker CLI (make sure this VM has docker install and logged in as user in a docker group)
  ansible.builtin.command:
    cmd: docker ps
  register: docker_output
  until:
    - "'docker: command not found' not in docker_output.stderr"
    - "'permission denied' not in docker_output.stdout"
  retries: 10
  delay: 10
  changed_when: true
  become_user: '{{ ansible_user }}'

- name: Pull rancher server image
  ansible.builtin.command:
    cmd: docker image pull rancher/rancher:{{ rancher_server_version }}
  become_user: '{{ ansible_user }}'

- name: Provision rancher server docker container
  ansible.builtin.command:
    cmd: docker run --name rancher-server -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:{{ rancher_server_version }}
  become_user: '{{ ansible_user }}'

- name: Successfully deployed Rancher Server
  debug:
    msg: "Visit Rancher at: https://{{ hostvars[groups['rancher'][0]]['ansible_host'] }}/dashboard/auth/login. You will now need to manually follow the instructions to connect Rancher with the RKE2 cluster"
