- name: Create directory for RKE2 config
  ansible.builtin.file:
    path: '/etc/rancher/rke2'
    state: directory
    mode: '0644'
  become: true
  when: inventory_hostname == groups['servers'][0]

- name: Deploy RKE2 server Configuration
  ansible.builtin.template:
    src: templates/rke2-server1-config.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: '0644'
  become: true
  when: inventory_hostname == groups['servers'][0]

- name: Enable RKE2 server service to start on boot
  ansible.builtin.systemd:
    name: rke2-server
    enabled: yes
  become: true
  when: inventory_hostname == groups['servers'][0]

- name: Start RKE2 server service
  ansible.builtin.systemd:
    name: rke2-server
    state: started
  become: true
  when: inventory_hostname == groups['servers'][0]

- name: Copy kubectl to user bin
  ansible.builtin.copy:
    src: /var/lib/rancher/rke2/bin/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
    remote_src: true
  become: true
  when: inventory_hostname == groups['servers'][0]

- name: Ensure .kube directory exists in user's home
  ansible.builtin.file:
    path: '/home/{{ ansible_user }}/.kube'
    state: directory
    owner: '{{ ansible_user }}'
    mode: '0755'
  become_user: '{{ ansible_user }}'
  when: inventory_hostname == groups['servers'][0]

- name: Copy config file to user home directory
  ansible.builtin.copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: '/home/{{ ansible_user }}/.kube/config'
    remote_src: true
    owner: '{{ ansible_user }}'
    mode: '0755'
  when: inventory_hostname == groups['servers'][0]

- name: Change kubeconfig server address to Kube VIP
  ansible.builtin.command:
    cmd: kubectl config set-cluster default --server=https://{{ vip }}:6443 --kubeconfig=/home/{{ ansible_user }}/.kube/config
  become_user: '{{ ansible_user }}'
  when: inventory_hostname == groups['servers'][0]

- name: Wait for cluster API to be ready, and for Kube VIP to be available
  ansible.builtin.command:
    cmd: kubectl get nodes
  register: kubectl_output
  until:
    - "'connect: no route to host' not in kubectl_output.stderr"
    - "'NotReady' not in kubectl_output.stdout"
  retries: 120
  delay: 10
  changed_when: true
  become_user: '{{ ansible_user }}'
  when: inventory_hostname == groups['servers'][0]
