- name: Download haproxy
  ansible.builtin.shell:
    cmd: apt install haproxy -y
  become: true

- name: Copy haproxy config file for servers
  ansible.builtin.template:
    src: templates/haproxy-config.j2
    dest: /etc/haproxy/haproxy.cfg
    owner: root
    group: root
    mode: '0644'
  become: true

- name: Start haproxy service on master server
  ansible.builtin.systemd_service:
    name: haproxy
    state: reloaded
  become: true
