- name: Create directory for RKE2 config
  ansible.builtin.file:
    path: '/etc/rancher/rke2'
    state: directory
    owner: root
    group: root
    mode: '0644'
  become: true
  when: inventory_hostname in groups['agents']

- name: Deploy RKE2 Agent Configuration
  ansible.builtin.template:
    src: templates/rke2-agent-config.j2
    dest: /etc/rancher/rke2/config.yaml
    owner: root
    group: root
    mode: '0644'
  become: true
  when: inventory_hostname in groups['agents']

- name: Enable and start RKE2 agent service
  ansible.builtin.systemd_service:
    name: rke2-agent
    enabled: yes
  become: true
  when: inventory_hostname in groups['agents']

- name: Enable and start RKE2 agent service
  ansible.builtin.systemd_service:
    name: rke2-agent
    state: reloaded
  become: true
  when: inventory_hostname in groups['agents']
