- name: Wait for server1 to be ready
  ansible.builtin.command:
    cmd: kubectl wait --for=condition=Ready nodes --selector server=true --timeout=100s
  retries: 60
  delay: 10
  changed_when: true
  become_user: '{{ ansible_user }}'
  when: inventory_hostname == groups['servers'][0]

- name: Apply metallb manifest
  ansible.builtin.command:
    cmd: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/{{ metallb_version }}/config/manifests/metallb-native.yaml
  become_user: '{{ ansible_user }}'
  when: inventory_hostname == groups['servers'][0]

- name: Wait for metallb pods to be ready, otherwise we cannot start metallb deployment
  ansible.builtin.command:
    cmd: kubectl wait --namespace metallb-system --for=condition=ready pod --selector=component=controller --timeout=100s
  retries: 60
  delay: 10
  changed_when: true
  become_user: '{{ ansible_user }}'
  when: inventory_hostname == groups['servers'][0]

- name: Copy metallb L2-Advertisement to server1
  ansible.builtin.template:
    src: templates/metallb-l2advertisement.j2
    dest: /home/{{ ansible_user }}/l2-advertisement.yaml
    mode: '0755'
  become_user: '{{ ansible_user }}'
  when: inventory_hostname == groups['servers'][0]

- name: Apply metallb manifest
  ansible.builtin.command:
    cmd: kubectl apply -f /home/{{ ansible_user }}/l2-advertisement.yaml
  become_user: '{{ ansible_user }}'
  when: inventory_hostname == groups['servers'][0]

- name: Copy metallb IPPool to server1
  ansible.builtin.template:
    src: templates/metallb-ippool.j2
    dest: /home/{{ ansible_user }}/ippool.yaml
    mode: '0755'
  become_user: '{{ ansible_user }}'
  when: inventory_hostname == groups['servers'][0]

- name: Apply metallb ipppool
  ansible.builtin.command:
    cmd: kubectl apply -f /home/{{ ansible_user }}/ippool.yaml
  become_user: '{{ ansible_user }}'
  when: inventory_hostname == groups['servers'][0]
